Module4 task1
htmlacademy-nodejs/829185-buy-and-sell-3 pull request #10
Opened 2021-04-30 20:39 UTC by loosq

2021-05-02 17:34 UTC, Krabaton requested changes

2021-05-02 17:34 UTC, Krabaton commented on package.json
> +    "nanoid": "^3.1.22",
Переустановить с флагом -E

2021-05-02 17:34 UTC, Krabaton commented on src/service/cli/generate.js
> +      const content = JSON.stringify(generateOffers(countOffer, titles, categories, sentences, comments));
Лучше создать параметр 
```
options = { titles, categories, sentences, comments }
```
И его передавать в функцию

2021-05-02 17:34 UTC, Krabaton commented on src/service/cli/server.js
>  app.use(express.json());
Выставь limit, там по умолчанию пол мегабайта
```
app.use(express.json({limit: 100000}));
```
100Kb

2021-05-02 17:34 UTC, Krabaton commented on src/service/api/offers.js
> +  route.get(`/`, (req, res) => res.status(HTTP_CODES.OK).json(offersService.findAll()));
Все handlers будут асинхронными. Почему не присвоить результат, а потом передавать данные. 
```
const result = await offersService.findAll()
```
После `result`, возможно мы данные будем менять от сервиса.  В чем экономия не присвоить данные переменной, а сразу выполнение функции передавать в res.json?

2021-05-03 16:19 UTC, loosq commented on src/service/api/offers.js
> +  route.get(`/`, (req, res) => res.status(HTTP_CODES.OK).json(offersService.findAll()));
Хорошая идея, добавил

2021-05-03 16:19 UTC, loosq commented on src/service/cli/server.js
>  app.use(express.json());
не знал про опции, добавил в константы

2021-05-03 16:19 UTC, loosq commented on src/service/cli/generate.js
> +      const content = JSON.stringify(generateOffers(countOffer, titles, categories, sentences, comments));
свёл в 1 объект

2021-05-03 16:21 UTC, loosq commented on package.json
> +    "nanoid": "^3.1.22",
ааа теперь стало понятно про save-exact, спасибо :)

2021-05-03 16:21 UTC, loosq commented
добавил src/service/api/api_test.http если надо быстро просканить запросы

2021-05-04 07:28 UTC, merged